project:
  type: website
  output-dir: docs

website:
  description: "Personal Website for Darren Shoemaker"
  site-url: https://your-website-url.example.com
  title: "thedungeonecologist"
  
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Blog
        href: posts.qmd
      - text: CV
        href: cv.qmd
      - icon: github
        href: https://github.com/thedungeonecologist
      - icon: linkedin
        href: https://www.linkedin.com/in/darrenshoemaker/
    
  page-footer:
    center: "[Darren Shoemaker](https://thedungeonecologist.github.io/darrenshoemaker/) &copy; 2026"
    right: "Built with Quarto"
    
  page-navigation: true

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css